del /s /q *.aux
del /s /q *.bcf
del /s /q *.bbl
del /s /q *.blg
del /s /q *.dvi
del /s /q *.fdb_latexmk
del /s /q *.fls
del /s /q *.gz
del /s /q *.log
del /s /q *.out
del /s /q *.toc
del /s /q *.vrb
del /s /q *.xml
del /s /q *.lof
del /s /q *.lot
del /s /q *.loa
del /s /q *.nav
del /s /q *.snm
del /s /q *.pygtex
del /s /q *.pygstyle
del /s /q *.listing